[package]
name = "any2utf8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chardetng = "0.1.17"
encoding_rs = "0.8.33"

[profile.release]
strip = true
lto = true
opt-level = 3